### ISSUE TITLE
[Feature Request] Show library/source name (not just logo) in LibraryStatisticsView

### ISSUE THREAD

**Issue by sukarn-m** [felixkmh/DuplicateHider#108]
In the LibraryStatisticsView as shown below, an icon is shown, along with the number of games and number of duplicates. Additionally, a fourth (empty) column is drawn.

**LibraryStatisticsView by itself:**
![image](https://user-images.githubusercontent.com/10946339/188909358-061986e7-a19f-4e06-b703-1bff1af0781c.png)

**Feature request:**
Show the Library Name in this view. The file DuplicateHider/source/Views/StartPage/LibraryStatisticsView.xaml seems to contain commented out code for showing the library name. If the library name was commented out to keep this column thin, then ideally, the view should be configurable in the extension's settings to enable or disable the library name.

When LibraryStatisticsView is arranged in a vertical column along with other Views, enough free space is left for the library name to be shown.

**LibraryStatisticsView with other Views in a single vertical column:**
![image](https://user-images.githubusercontent.com/10946339/188914783-379866ca-a08d-4d83-b9dc-dde35efb56e8.png)

**Comment by felixkmh** [comment]
Done in v3.14.0
