### ISSUE TITLE
Resource error "DuplicateHider_MaxNumberOfIcons"

### ISSUE THREAD

**Issue by darklinkpower** [felixkmh/DuplicateHider#11]
Saw this while I was debugging an extension, there were a ton of lines like this

![image](https://user-images.githubusercontent.com/1389286/132476940-e35f88ed-8f4d-483b-99c6-883db62f09c7.png)

Settings:
![image](https://user-images.githubusercontent.com/1389286/132477060-98872f1a-09f7-44df-854c-27e9c62ffbe2.png)

**Comment by felixkmh** [comment]
this is probably because there is no 
<sys:Int32 x:Key="DuplicateHider_MaxNumberOfIcons">4</sys:Int32>
resource in your themes Constants.xaml. As a workaround you could add that for the moment. I will fix the warnings later.

**Comment by darklinkpower** [comment]
Oh yeah must be that, thanks for the info.
