### ISSUE TITLE
Missing UI integration button

### ISSUE THREAD

**Issue by YaroslavKormushyn** [felixkmh/DuplicateHider#124]
Hi!
First off, great plugin! You did a great job on this one, this really helps manage the library with all of the different launchers we're now stuck with.

I enabled the UI integration within the plugin settings and restarted Playnite.
However, for a game that has copies in Steam and Epic, the button with the dropdown of available copies does not show up.
![image](https://github.com/felixkmh/DuplicateHider/assets/11539004/2e20a20f-e47d-4e41-80d5-7fabacea5fd6)

I'm using the default theme for Playnite, didn't change anything.

Platform: Windows 11 22H2 22621.2283
Playnite: 10.19
DuplicateHider: 3.14.5
Language: Ukrainian

**Comment by felixkmh** [comment]
Hi, custom UI elements, like the ones DuplicateHider uses, need explicit support by the theme. The default theme for Playnite does not have support for any custom UI element. Many of the custom themes available [here](https://playnite.link/addons.html) have some kind of support for DuplicateHider. If you like the look of the default theme, then there is this https://playnite.link/addons.html#playnite-defaultextend-theme

**Comment by YaroslavKormushyn** [comment]
Got it. Installed the DH Night theme, looks awesome! Also, the integration works now, so thanks for pointing that out.
However, it wasn't clear to me from the README that the default theme does not allow for custom UI elements.

@felixkmh would it make sense to state this explicitly in the README where the UI integration section is? You could add a link to the DH Night theme or the defaultextend theme there.

Closing this issue.
