### ISSUE TITLE
Humble Titles

### ISSUE THREAD

**Issue by livejamie** [felixkmh/DuplicateHider#138]
I'm sure there's a way for the plugin to handle Humble titles that appear like this

![image](https://github.com/user-attachments/assets/adb4eae0-c476-42b8-9e74-ddd4a0e1d4b0)

Is this something I can configure in the settings or would the plugin need to be updated?

**Comment by felixkmh** [comment]
Under "Custom Rules" you can define replacement rules that are applied to game titles before checking for duplicates (the actual title of your games are not affected, its just for processing).
You could define rules for each launcher that replaces the launcher in parentheses, e.g. `(Steam)`, or `(GOG)` with an empty string.
You can also use regular expressions (requires the Regex checkbox to be checked):
- `\(.+\)` matches any non-empty string inside parentheses, including the parentheses
- `\((Steam|Epic Games Store|GOG)\)` matches either `(Steam)`, `(Epic Games Store)` or `(GOG)`, you can of course add other launchers here.

**Comment by livejamie** [comment]
Thanks!
