### ISSUE TITLE
Fails to load on Playnite 8.15 with SDK version error

### ISSUE THREAD

**Issue by btorresgil** [felixkmh/DuplicateHider#18]
On Playnite 8.15, this extension fails to load. Playnite is in portable mode, fresh install.

The file `playnite.log` contains this:

```
02-10 09:34:50.416|ERROR|ExtensionFactory:Plugin doesn't support current version of Playnite SDK, supports 6.0.0.0
02-10 09:34:50.416|ERROR|ExtensionFactory:Plugin dependencices are not compatible: DuplicateHider
```
![2021-10-02_10-48-52](https://user-images.githubusercontent.com/4164289/135727028-8427ee37-c776-4ee7-9659-e449a4ba37f5.png)

![2021-10-02_10-49-13](https://user-images.githubusercontent.com/4164289/135727029-4527d39b-833b-48ad-819a-9579318ade16.png)

**Comment by felixkmh** [comment]
The version you are trying to run is v3.2.3. Starting with version 3.0.0, the releases are no longer compatible with Playnite 8, only with the Playnite 9 Beta and the upcoming full release of Playnite 9. The latest version compatible with Playnite 8.15, is v2.5.4: https://github.com/felixkmh/DuplicateHider/releases/tag/v2.5.4
I guess I could have made that clearer, as the notes for the 3.0.0 release are the only place you could find that info in the notes.
