### ISSUE TITLE
Does not work in Playnite 9

### ISSUE THREAD

**Issue by Prelaps** [felixkmh/DuplicateHider#24]
I have just installed the latest version that is compatible with Playnite 9 but it does not seem to do anything. I tried hiding games through the extension menu and it says "Games Hidden: 0". I have a ton of duplicates so it should definitely find them.

Some of my duplicates
![image](https://user-images.githubusercontent.com/17280314/137594520-6d366712-2f53-4694-a6d8-5fb4f9650f95.png)

Results from extension
![image](https://user-images.githubusercontent.com/17280314/137594529-1922da95-03cf-41f7-a959-814efbda9f74.png)

**Comment by felixkmh** [comment]
Another thing you could do to help me figure this out is to check the playnite.log and extensions.log file for warnings or errors when trying to hide duplicates.
