### ISSUE TITLE
Extension causes two extra ItemUpdateEvent events in games

### ISSUE THREAD

**Issue by darklinkpower** [felixkmh/DuplicateHider#26]
While working on an extension, I noticed that `ItemUpdateEvent` were being triggered three times (an extra 2) for any changes. While investigating, I found that the 2 extra events were caused by the DuplicateHider extension. This can be used to verify this and happens when clicking "Save" from the game edit window even if no data in the game changes:

```csharp
PlayniteApi.Database.Games.ItemUpdated += (sender, itemUpdatedArgs) =>
{
    foreach (ItemUpdateEvent<Game> updatedItem in itemUpdatedArgs.UpdatedItems)
    {
        PlayniteApi.Dialogs.ShowMessage("ItemUpdateEvent triggered");
    }
};
```

Is there a reason why this happens? I assume DuplicateHider is modifying something in the game multiple times, which causes the even to be triggered multiple times but I don't know if this is intended.

**Comment by felixkmh** [comment]
But I still don't get why you would get 2 extra triggers from DH, because I only seem to get 1. Could you check if the updates are empty or if they change the Hidden field? This is the only case in which I call the Games.Update() function at all.

**Comment by felixkmh** [comment]
[felixkmh_DuplicateHider_Plugin_3_4_1.zip](https://github.com/felixkmh/DuplicateHider/files/7363628/felixkmh_DuplicateHider_Plugin_3_4_1.zip)
I added a check to only call it with non-empty Lists, so try it with this one.
