### ISSUE TITLE
[request] synchronize media data with duplicated games

### ISSUE THREAD

**Issue by shakeyourbunny** [felixkmh/DuplicateHider#31]
Would it be possible to synchronize the media data for all duplicates (with extra metada if present?), so that the duplicates have some sort of uniform look to it and not every copy has its own background picture, logo, icon, screenshots etc?

The default metadata import does its job decently, but in cases where the name slightly varies (e.g. added some "demo", "game of the year", "collectors edition", roman numerals instead of arabic ones ( II -> 2)) it may happen that the metadata may get jumbled.

Should be some sort of checkbox field for the metadata.

Could be called (as a tab) "synchronize metadata" or something.

**Comment by erys** [comment]
I'm currently in the process of manually syncing metadata between duplicates, and it's a real pain. Having this functionality would be very useful, especially if we could choose which copy to keep each bit of metadata from, similar to how it works when downloading metadata that would overwrite existing fields. (I am also now wondering if there would be a way to make a metadata extension that did this, treating the other copies as a metadata source)

**Comment by felixkmh** [comment]
This is definitely something I want to add in some shape or form, but I haven't made up my mind on how exactly I want to approach this. Probably something simple, that will allow you to select a source copy and which fields you want to copy over to all the other copies.

**Comment by felixkmh** [comment]
In v3.8.0, I added a game menu entry that allows users to copy selected fields/assets from selected game(s) to all its/their copies, including ExtraMetadata. But I don't think I will automate this functionality. I feel like it could easily lead to results the user might not want.
