### ISSUE TITLE
Include Demos in folding as a copy

### ISSUE THREAD

**Issue by shakeyourbunny** [felixkmh/DuplicateHider#32]
Hi,

would it be possible to automatically have demos (games end with "demo" or "Demo") folded into a copy?

eg "Kathy Rain" + "Kathy Rain Demo" would be folded into one game.

**Comment by felixkmh** [comment]
You can already do that using the custom replacement rules. Just put
```
[\s-(\[]Demo[)\]]?$
```
into the left side of a rule and leave the right side empty and check the regex checkbox. This will match the word "demo" (case insensitive) at the end of a game name, possibly enclosed by () or [], and replace it with nothing for further processing.
