### ISSUE TITLE
Xbox games dont seem to group with other games

### ISSUE THREAD

**Issue by MoulikRT** [felixkmh/DuplicateHider#34]
Unless I have done something wrong with the priority levels, any XBox game doesnt seem to be hidden with its regular pc counterparts. 
Unfortunately, there are too many overlapping xbox games for me to set up a custom group for each of them.
Example:
![Screenshot 2021-11-04 141322](https://user-images.githubusercontent.com/46884813/140283641-14ccf57a-5a31-4671-879d-a2a96eefaf37.png)

**Comment by felixkmh** [comment]
Only PC games are hidden by default. You can enable other platforms in the options under "Included Platforms".

**Comment by MoulikRT** [comment]
Thank you very much! Worked like a charm.
