### ISSUE TITLE
[request] select a category or tag to indicate that copy should be deprecated, regardless of the priority list

### ISSUE THREAD

**Issue by EloquenceWinters** [felixkmh/DuplicateHider#35]
I'd like to be able to select a category/tag and have DH manually place any copy of a game that has that category/tag at the bottom of the priority list, regardless of where it would otherwise be placed.

Use case: I typically prefer to play games via Steam, but Assassin's Creed II can't be shared via family sharing. Because the Steam copy in Playnite is on my son's account, I have it tagged as "unshareable," and I'd like DH to show me my copy on Ubisoft Connect instead of the Steam copy that I can't install or play. I hope that makes sense. :-)

I know I could exclude the category, but as I understand it, that would mean Playnite would show me both the Steam and the Ubisoft Connect copies, correct? I'd rather it still consolidate, just with a different prioritization. Thanks for considering it!

**Comment by felixkmh** [comment]
done via d15240ad8b8362945079b34c8d0513503e8e8f71. Tags ([DH] High, [DH] Low) can be used to overwrite the priority to either be the lowest or highest. Will be part of the next update.
