### ISSUE TITLE
[Feature request] Translate the {Installed} duplicate game string

### ISSUE THREAD

**Issue by BanCrash** [felixkmh/DuplicateHider#38]
Hi,

I've saw in Crowdin that Spanish has the 100% translated, but the {Installed} duplicate game string are showed in english:

![image](https://user-images.githubusercontent.com/11770760/140928223-a398ab5a-4bd3-4995-a359-205d8c3c668e.png)
![image](https://user-images.githubusercontent.com/11770760/140928846-8dfb43ef-dfe8-404c-8ebf-e4b27d35aa94.png)

The "Not installed" and "Installed" strings should appear in the language that you have on Playnite instead of english if they have a translation available.

**Comment by felixkmh** [comment]
fixed via 6ccd36692dbd548d5ad28b4ea549ef885b6c7a64

**Comment by BanCrash** [comment]
> fixed via [6ccd366](https://github.com/felixkmh/DuplicateHider/commit/6ccd36692dbd548d5ad28b4ea549ef885b6c7a64)

Thank you!
