### ISSUE TITLE
[Feature Request] export duplicate listings to CSV

### ISSUE THREAD

**Issue by shakeyourbunny** [felixkmh/DuplicateHider#54]
Hi,

would it be possible to export a list of duplicated games to a CSV or something similar, where the duplicate games are listed?

Fields would be for example:
game name ; primary platform ; secondary game name; secondary platform ; tertiary game name ; tertiary platform copy ; ....

Thank you!

**Comment by felixkmh** [comment]
done via 787490dc415fee18b173db42b5b92e4650c7fcf4

**Comment by shakeyourbunny** [comment]
Question: will be there a plugin release with the update too? Thank you!
