### ISSUE TITLE
"Prioritize newer game" setting does not persist through relaunching Playnite

### ISSUE THREAD

**Issue by lef-est** [felixkmh/DuplicateHider#57]
This setting works -- the change can be noticed immediately, but after I close Playnite and relaunch it, the change is reverted to the default (back to "on").

Edit: 
environment: Playnite 9.16 (latest stable), DuplicateHider 3.8.5 (latest stable), Windows 10

**Comment by felixkmh** [comment]
fixed via 54ded78733cfdf7c848dffdf1947d1940928e182
