### ISSUE TITLE
[Feature Request] Option to always prioritize certain Libraries (or use Libraries for "Priorities" instead of Sources)

### ISSUE THREAD

**Issue by lef-est** [felixkmh/DuplicateHider#58]
I use Source to distinguish where the key is purchased so I may have
A) Library Steam, Source Humble or Indiegala (Steam key from outside Steam)
B) Library Indiegala, Source Indiegala (Indiegala Showcase freebies)
C) Library Humble, Source Humble (DRM-free copies purchased or given away for free from Humble)

With the current sorting method, I can't prioritize Steam copies over Humble or Indiegala ones.

(If you think the way I use Playnite is idiosyncratic, I end up with this paradigm after reading this post https://www.reddit.com/r/playnite/comments/t0jkgp/difference_between_library_and_source/ )

**Comment by lef-est** [comment]
In the same vein, it would be nice if I could set the icons on the cover or details list to be representative of the library instead of the source...

**Comment by felixkmh** [comment]
done via ca4d440fc5ef7fae6c68685cb32ab0a7e2df6647

**Comment by lef-est** [comment]
omg thank you so much. this is much better than i requested!
