### ISSUE TITLE
Platforms appearing multiple time in Priorities dropdown

### ISSUE THREAD

**Issue by Jhanlon95** [felixkmh/DuplicateHider#78]
I was noticing that a couple of my games weren't prioritising properly, when I checked the dropdown in the add-on settings where you can define the priority for the "Platform" I was able to see a number of doubles for a bunch of platforms, I checked the "Library Manager" and there are only 1 of each platform added. I put the doubles beside each other and they resolved my problem but obviously can cause issues if it happens for others. Attached screenshot below

![Playnite DesktopApp_FUYLIj8ZnO](https://user-images.githubusercontent.com/11045596/171994098-b5b23f9c-9720-4eda-a822-281f30d64fcc.png)

**Comment by felixkmh** [comment]
fixed via f28b24592ae740b9427c20363855cd49cb8b8da3
