### ISSUE TITLE
Get game icons by pluginId instead of source to be more reliable.

### ISSUE THREAD

**Issue by darklinkpower** [felixkmh/DuplicateHider#9]
Currently the plugin seems to get the game icon by source name. This can be an issue since sources names can be changed by the user and will stop getting the icons, even though the actual source plugin is the same.

The plugin name can be obtained with this method: https://playnite.link/docs/devel/api/Playnite.SDK.BuiltinExtensions.html#Playnite_SDK_BuiltinExtensions_GetExtensionFromId_System_Guid_

Alternatively it could just use the plugin GUID to match the icons instead of getting the plugin Enum.

Then, if the pluginId doesn't find any plugin, then it could fallback to using the source.

**Comment by felixkmh** [comment]
Thanks for the suggestion. Do you also happen to know how the AddonId relates to the PluginId? Is it hashed somehow to retrieve a Guid?

**Comment by felixkmh** [comment]
Or put differently: is there a way to retrieve an AddinId from a given PluginId?

**Comment by felixkmh** [comment]
done with 19e3a0c58ec55ac0bbb3cb0531dd30e34798dfef

**Comment by darklinkpower** [comment]
Wow that was fast. Also just in case it helps in the future, I have the ids of all the builtin library plugins

```
Key                                               Value
---                                               -----
e3c26a3d-d695-4cb7-a769-5ff7612c7edd   BattleNetLibrary
0e2e793e-e0dd-4447-835c-c44a1fd506ec    BethesdaLibrary
00000002-dbd1-46c6-b5d0-b1ba559d10e4        EpicLibrary
aebe8b7c-6dc3-4a66-af31-e7375c6b5e9e         GogLibrary
00000001-ebb2-4eec-abcb-7c89937a42bb      ItchioLibrary
85dd7072-2f20-4e76-a007-41035e390724      OriginLibrary
cb91dfc9-b977-43bf-8e70-55f46e410fab       SteamLibrary
e2a7d494-c138-489d-bb3f-1d786beeb675      TwitchLibrary
c2f038e5-8b92-4877-91f1-da9094155fc5       UplayLibrary
000001db-dbd1-46c6-b5d0-b1ba559d10e4       IgdbMetadata
96e8c4bc-ec5c-4c8b-87e7-18ee5a690626      HumbleLibrary
7e4fbb5e-2ae3-48d4-8ba0-6b30e7a4e287        XboxLibrary
402674cd-4af6-4886-b6ec-0e695bfa0688 AmazonGamesLibrary
e4ac81cb-1b1a-4ec9-8639-9a9633989a71         PSNLibrary
```
